language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh

env:
  matrix:
    - TARGET=CI
    - TARGET=IT SQ_VERSION=5.2 JAVA_VERSION=3.8 JAVASCRIPT_VERSION=2.9 PHP_VERSION=2.7 PYTHON_VERSION=1.5
    - TARGET=IT SQ_VERSION=5.3 JAVA_VERSION=LATEST_RELEASE JAVASCRIPT_VERSION=LATEST_RELEASE PHP_VERSION=LATEST_RELEASE PYTHON_VERSION=LATEST_RELEASE
    - TARGET=IT SQ_VERSION=DEV JAVA_VERSION=LATEST_RELEASE JAVASCRIPT_VERSION=LATEST_RELEASE PHP_VERSION=LATEST_RELEASE PYTHON_VERSION=LATEST_RELEASE

cache:
  directories:
    - '$HOME/.m2/repository'
    # for integration tests and analysis
    - $HOME/.sonar

notifications:
  email: false
